### ISSUE TITLE
Enhancement Request: Include Site Name, Current Humidity

### ISSUE THREAD

**Issue by MizterB** [sdague/proliphix#1]
I have a Home Assistant implementation that communicates with a large number of Proliphix thermostats across several buildings.  To differentiate among them, I use a combination of the Device Name and Site Name OIDs - the Device Name alone is not enough.  Could you please include the Site Name OID (1.10.9) in the API?

Additionally, would it be possible to add thermRelativeHumidity (4.1.14) as well?

**Comment by sdague** [comment]
Sure, I can do that, I'll try to work up a commit for that this weekend. My proliphix thermostat was retired in November when we put in geothermal heating, so I'll ask you to test things before I cut new releases as I no longer have a live testing environment.

Work for you?

**Comment by sdague** [comment]
https://github.com/sdague/proliphix/commit/16a6b51c80393e665e958cad2ff625dc3 merged in *should* fix this. If you can:

pip install https://github.com/sdague/proliphix into one of your home assistant instances and restarted it, that should see if the naming shows up as expected. Once you confirm that it does, I'll release the library, and look at building a PR for the home assistant side to include the humidity portion there.

**Comment by sdague** [comment]
Released in 0.5.0

**Comment by MizterB** [comment]
Thank you for the quick turnaround!  I haven't yet had an opportunity to test - hoping to in the next few days.
